name: size_tailored_text
description: "This text widget automatically adjusts the font size to prevent overflow error messages by ensuring it does not exceed the given space."
version: 1.0.1
homepage: https://github.com/aqoong/size_tailored_text

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aqoong.plugin.ui.sizetailoredtext.size_tailored_text
        pluginClass: SizeTailoredTextPlugin
      ios:
        pluginClass: SizeTailoredTextPlugin

license: MIT