name: size_tailored_text
description: "This text widget automatically adjusts the font size to prevent overflow error messages by ensuring it does not exceed the given space."
version: 1.0.5
homepage: https://github.com/aqoong/size_tailored_text

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

license: MIT