name: size_tailored_text
description: "Size the text to the size of the parent widget."
version: 0.0.1
homepage: https://github.com/aqoong/size_tailored_text

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aqoong.plugin.ui.sizetailoredtext.size_tailored_text
        pluginClass: SizeTailoredTextPlugin
      ios:
        pluginClass: SizeTailoredTextPlugin

license: MIT