name: Flutter Version test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: [2.0.0, 2.2.0, 2.5.0, 2.8.0, 2.10.0, 2.12.0, 3.0.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter ${{ matrix.flutter-version }}
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test
